#! /usr/bin/env python2
#
#   File:       pnd
#   Author:     David Stanek
#   License:    GNU GPLv2 or newer
#

import getpass
import sys
from PN_Daemon import PN_Daemon

if __name__ == '__main__':
	# Read passphrase to decrypt server's private key (this key is used to decrypt requests from clients)
	if len(sys.argv) == 1:
		passphrase = getpass.getpass("Server's private key passphrase:")
	else:
		passphrase = sys.argv[1]

	daemon = PN_Daemon()
	daemon.run(passphrase)

