#! /usr/bin/env python2
#
#   File:       pnd
#   Author:     David Stanek
#   License:    GNU GPLv2 or newer
#

import getpass
import sys
from PN_Daemon import PN_Daemon

if __name__ == '__main__':
	daemon = PN_Daemon()
	daemon.run()

